#!/bin/bash

# Invite Acceptance Smoke Test Checklist
# 
# This script provides a manual testing checklist for the invite acceptance flow.
# Run each scenario and verify the expected outcomes.

set -e

echo "=========================================="
echo "INVITE ACCEPTANCE SMOKE TEST CHECKLIST"
echo "=========================================="
echo ""
echo "This is a MANUAL test checklist. Follow each scenario step-by-step."
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test scenarios
echo "=========================================="
echo "SCENARIO A: Logged-Out User Clicks Invite Link"
echo "=========================================="
echo ""
echo "Steps:"
echo "  1. Ensure you are logged out"
echo "  2. Click an invite link: /accept-invite?token=VALID_TOKEN"
echo "  3. Observe the page"
echo ""
echo "Expected Outcomes:"
echo "  ✓ Page loads WITHOUT redirecting to /"
echo "  ✓ Invite Landing page is shown (or AcceptInvitationPage if token valid)"
echo "  ✓ returnTo=/accept-invite?token=... is stored in storage"
echo "  ✓ 'Log In' and 'Sign Up' buttons are visible"
echo ""
echo "Verification Commands:"
echo "  - Open DevTools Console"
echo "  - Check for: [InviteTokenParser] Parsed from URL"
echo "  - Check for: [AuthGuard] On public route, allowing access: /accept-invite"
echo "  - Check localStorage: RETURN_URL should contain /accept-invite?token=..."
echo ""
read -p "Press Enter when ready to continue to Scenario B..."

echo ""
echo "=========================================="
echo "SCENARIO B: Logged-Out User Signs Up via Invite"
echo "=========================================="
echo ""
echo "Steps:"
echo "  1. From Scenario A, click 'Create Account & Accept'"
echo "  2. Fill out signup form (First Name, Last Name, Email, Password)"
echo "  3. Check 'Agree to Terms'"
echo "  4. Click 'Create Account & Connect'"
echo "  5. Wait for account creation and acceptance"
echo ""
echo "Expected Outcomes:"
echo "  ✓ Form validation works (shows errors if fields invalid)"
echo "  ✓ Account is created successfully"
echo "  ✓ Invitation is accepted (POST /api/invites/accept called ONCE)"
echo "  ✓ User is redirected to / (dashboard) after 1.5s"
echo "  ✓ Success message: 'Account created and connected! Redirecting...'"
echo ""
echo "Verification Commands:"
echo "  - Open DevTools Network tab"
echo "  - Verify: POST /api/auth/register-with-invite (200)"
echo "  - Verify: POST /api/invites/accept called EXACTLY ONCE (200)"
echo "  - Check console: [InviteAccept] Signup successful"
echo "  - Check console: [InviteAccept] Auto-accept result: success: true"
echo "  - Check console: [InviteAccept] Redirecting after success: /"
echo ""
read -p "Press Enter when ready to continue to Scenario C..."

echo ""
echo "=========================================="
echo "SCENARIO C: Logged-Out User Logs In via Invite"
echo "=========================================="
echo ""
echo "Steps:"
echo "  1. From Scenario A, click 'Log In to Accept'"
echo "  2. Enter credentials and log in"
echo "  3. Wait for redirect and acceptance"
echo ""
echo "Expected Outcomes:"
echo "  ✓ Redirects to /signin?returnTo=/accept-invite?token=..."
echo "  ✓ After login, redirects back to /accept-invite?token=..."
echo "  ✓ Invitation is auto-accepted (POST /api/invites/accept called ONCE)"
echo "  ✓ User is redirected to / (dashboard) after 1.5s"
echo "  ✓ Success message: 'Connected with your co-parent! Redirecting...'"
echo ""
echo "Verification Commands:"
echo "  - Check console: [AuthGuard] Stored return URL: /accept-invite?token=..."
echo "  - Check console: [useAuthRedirect] Redirecting to stored return URL"
echo "  - Verify: POST /api/invites/accept called EXACTLY ONCE (200)"
echo "  - Check console: [InviteAccept] Auto-accept result: success: true"
echo ""
read -p "Press Enter when ready to continue to Scenario D..."

echo ""
echo "=========================================="
echo "SCENARIO D: Logged-In User Clicks Invite Link"
echo "=========================================="
echo ""
echo "Steps:"
echo "  1. Ensure you are logged in"
echo "  2. Click an invite link: /accept-invite?token=VALID_TOKEN"
echo "  3. Wait for auto-acceptance"
echo ""
echo "Expected Outcomes:"
echo "  ✓ Page loads WITHOUT redirecting to /"
echo "  ✓ Token is validated"
echo "  ✓ Invitation is auto-accepted (POST /api/invites/accept called ONCE)"
echo "  ✓ User is redirected to / (dashboard) after 1.5s"
echo "  ✓ Success message: 'Connected with your co-parent! Redirecting...'"
echo ""
echo "Verification Commands:"
echo "  - Check console: [InviteAccept] Token read"
echo "  - Check console: [InviteAccept] Validation result: valid: true"
echo "  - Check console: [InviteAccept] Starting auto-accept"
echo "  - Verify: POST /api/invites/accept called EXACTLY ONCE (200)"
echo "  - Check console: [InviteAccept] Auto-accept result: success: true"
echo ""
read -p "Press Enter when ready to continue to Error Scenarios..."

echo ""
echo "=========================================="
echo "ERROR SCENARIOS"
echo "=========================================="
echo ""
echo "E1. Invalid Token"
echo "  - Visit: /accept-invite?token=INVALID_TOKEN"
echo "  - Expected: InvalidTokenView with 'Invalid invitation link' message"
echo "  - Expected: 'Sign In' and 'Go to Home' buttons"
echo ""
echo "E2. Expired Token"
echo "  - Visit: /accept-invite?token=EXPIRED_TOKEN"
echo "  - Expected: InvalidTokenView with 'This invitation has expired' message"
echo ""
echo "E3. Already Accepted Token"
echo "  - Visit: /accept-invite?token=ALREADY_ACCEPTED_TOKEN"
echo "  - Expected: InvalidTokenView or success message if logged in"
echo ""
echo "E4. Wrong Account (Logged in with different email)"
echo "  - Log in with email A"
echo "  - Visit: /accept-invite?token=TOKEN_FOR_EMAIL_B"
echo "  - Expected: WrongAccountView with email mismatch message"
echo "  - Expected: 'Switch Account' button"
echo ""
read -p "Press Enter to finish..."

echo ""
echo "${GREEN}=========================================="
echo "SMOKE TEST CHECKLIST COMPLETE"
echo "==========================================${NC}"
echo ""
echo "If all scenarios passed, the invite acceptance flow is working correctly."
echo ""

