/**
 * Blog Image Mapping
 * 
 * Auto-generated mapping of blog article slugs to their header images.
 * Generated by: scripts/generate-all-blog-images.js
 * Generated at: 2025-12-24T19:13:55.370Z
 * 
 * Usage in components:
 *   import { blogImageMap } from './blogImageMap';
 *   const imagePath = blogImageMap['article-slug'];
 */

export const blogImageMap = {
  'emotional-triggers': '/assets/blog-images/emotional-triggers-header.png',
  'emotional-regulation': '/assets/blog-images/emotional-regulation-header.png',
  'reaction-vs-response': '/assets/blog-images/reaction-vs-response-header.png',
  'pause-before-reacting': '/assets/blog-images/pause-before-reacting-header.png',
  'defensiveness-strategies': '/assets/blog-images/defensiveness-strategies-header.png',
  'why-it-feels-impossible': '/assets/blog-images/why-it-feels-impossible-header.png',
  'de-escalation-techniques': '/assets/blog-images/de-escalation-techniques-header.png',
  'gaslighting-guilt-blame': '/assets/blog-images/gaslighting-guilt-blame-header.png',
  'mental-health-protection': '/assets/blog-images/mental-health-protection-header.png',
  'long-term-effects': '/assets/blog-images/long-term-effects-header.png',
  'how-ai-mediation-works': '/assets/blog-images/how-ai-mediation-works-header.png',
  'calm-communication-ai': '/assets/blog-images/calm-communication-ai-header.png',
  'ai-safety-for-parents': '/assets/blog-images/ai-safety-for-parents-header.png',
};

// Helper function to get image path for an article
export function getBlogImage(slug) {
  return blogImageMap[slug] || null;
}
